"""Add government_reference to Application

Revision ID: 3d97ccee5271
Revises: cc438f2aa62c
Create Date: 2026-09-19 12:39:16.806963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d97ccee5271'
down_revision: Union[str, None] = 'cc438f2aa62c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('government_reference', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_applications_government_reference'), 'applications', ['government_reference'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_government_reference'), table_name='applications')
    op.drop_column('applications', 'government_reference')
    # ### end Alembic commands ###
