"""Add government_status to applications

Revision ID: 6ad05b3a21c6
Revises: b7a9c0757a31
Create Date: 2026-09-19 13:40:35.277825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad05b3a21c6'
down_revision: Union[str, None] = 'b7a9c0757a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('government_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'government_status')
    # ### end Alembic commands ###
