"""Phase 5 models

Revision ID: b7a9c0757a31
Revises: 3d97ccee5271
Create Date: 2026-09-19 12:56:52.794032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7a9c0757a31'
down_revision: Union[str, None] = '3d97ccee5271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('actor_type', sa.String(length=50), nullable=False))
    op.add_column('audit_logs', sa.Column('actor_id', sa.String(length=255), nullable=True))
    op.add_column('consents', sa.Column('application_id', sa.UUID(), nullable=False))
    op.add_column('consents', sa.Column('requesting_department', sa.String(length=100), nullable=False))
    op.add_column('consents', sa.Column('data_requested', sa.JSON(), nullable=False))
    op.add_column('consents', sa.Column('data_snapshot', sa.JSON(), nullable=False))
    op.add_column('consents', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('consents', sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True))
    bind = op.get_bind()
    if bind.dialect.name == 'sqlite':
        with op.batch_alter_table('consents') as batch_op:
            batch_op.create_foreign_key('fk_consents_applications', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
            batch_op.drop_column('granted')
            batch_op.drop_column('data_scopes')
    else:
        op.create_foreign_key(None, 'consents', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
        op.drop_column('consents', 'granted')
        op.drop_column('consents', 'data_scopes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consents', sa.Column('data_scopes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('consents', sa.Column('granted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'consents', type_='foreignkey')
    op.drop_column('consents', 'responded_at')
    op.drop_column('consents', 'status')
    op.drop_column('consents', 'data_snapshot')
    op.drop_column('consents', 'data_requested')
    op.drop_column('consents', 'requesting_department')
    op.drop_column('consents', 'application_id')
    op.drop_column('audit_logs', 'actor_id')
    op.drop_column('audit_logs', 'actor_type')
    # ### end Alembic commands ###
