"""Add required_fields to services

Revision ID: b89de0d45258
Revises: 1f68736d7f13
Create Date: 2026-09-19 11:57:00.503615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b89de0d45258'
down_revision: Union[str, None] = '1f68736d7f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('required_fields', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'required_fields')
    # ### end Alembic commands ###
