"""Add verification_status and extracted_data to documents

Revision ID: cc438f2aa62c
Revises: b89de0d45258
Create Date: 2026-09-19 12:21:14.575974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc438f2aa62c'
down_revision: Union[str, None] = 'b89de0d45258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('application_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('verification_status', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('extracted_data', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'documents', 'applications', ['application_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'extracted_data')
    op.drop_column('documents', 'verification_status')
    op.drop_column('documents', 'application_id')
    # ### end Alembic commands ###
